[package]
name = "Mojo Monsters"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../aptos_framework/aptos-framework" }
AptosTokenObjects = { local = "../aptos_framework/aptos-token-objects" }

[addresses]
aptos_framework = "0x1"
aptos_token_objects = "0x4"
mojo_monsters = "_"

[dev-addresses]
mojo_monsters="0xbeefcafe"
